import { CensusAnalysis } from '@/lib/models/census';
import { reportStyles } from './styles';
import { reportScripts } from './scripts';
import {
  renderFearGreedGauge,
  renderMetricsGrid,
  renderAllDistributions,
  renderHoldingsTable,
  renderPerformersTable
} from './components';

export interface AnalysisBand {
  count: number;
  analysis: CensusAnalysis;
}

function renderTabContent(item: AnalysisBand, index: number): string {
  const { count, analysis } = item;

  return `
    <div class="tab-content ${index === 0 ? 'active' : ''}" id="tab-${index}">
      ${renderFearGreedGauge(analysis)}
      ${renderMetricsGrid(analysis)}
      ${renderAllDistributions(analysis, count)}

      <!-- Tables -->
      <div class="space-y-8" style="margin-top: 2rem;">
        ${renderHoldingsTable(analysis.topHoldings || [], index, count)}
        ${renderPerformersTable(analysis.topPerformers || [], index, count)}
      </div>
    </div>
  `;
}

export function generateReportHTML(analyses: AnalysisBand[], generatedAt: string): string {
  console.log(`HTML Generator received ${analyses.length} analyses`);
  analyses.forEach((item, idx) => {
    console.log(`  Analysis ${idx}: count=${item.count}, holdings=${item.analysis?.topHoldings?.length || 0}, performers=${item.analysis?.topPerformers?.length || 0}`);
  });

  const tabs = analyses.map((item, index) => `
    <button class="tab ${index === 0 ? 'active' : ''}" onclick="showTab(${index})">
      Top ${item.count} PIs
    </button>
  `).join('');

  const tabContents = analyses.map((item, index) => renderTabContent(item, index)).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>eToro Census Report - ${new Date().toLocaleDateString()}</title>
    <script defer src="https://cloud.umami.is/script.js" data-website-id="5730b8f9-c50c-4175-9d28-50db8bfb04dc"></script>
    <style>
        ${reportStyles}
    </style>
</head>
<body>
    <div class="header">
        <div class="header-content">
            <h1>eToro Popular Investors Census</h1>
            <p class="creator">created by <a href="https://www.etoro.com/people/plessas" target="_blank" rel="noopener noreferrer">@plessas</a> at ${generatedAt}</p>
        </div>
    </div>

    <div class="container">
        <!-- Tabs -->
        <div class="tabs">
            ${tabs}
        </div>

        <!-- Tab Contents -->
        ${tabContents}
    </div>

    <div class="footer">
        <p>Generated by <a href="https://github.com/weirdapps/etoro_census" target="_blank">eToro Census Tool</a> - Optimized Architecture</p>
        <p>Data sourced from eToro's API - Tool created by <a href="https://www.etoro.com/people/plessas" target="_blank" rel="noopener noreferrer">@plessas</a>, not affiliated with eToro.</p>
    </div>

    <script>
        ${reportScripts}
    </script>
</body>
</html>`;
}

// Re-export for convenience
export * from './utils';
export * from './components';
