name: Deploy Reports to GitHub Pages

on:
  push:
    branches: [ main, master ]
    paths:
      - 'public/reports/**'
      - '.github/workflows/deploy-reports.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Copy latest report to index.html
        run: |
          cd public/reports
          # Find the most recent report file (excluding index.html)
          LATEST_REPORT=$(ls -t etoro-census-*.html 2>/dev/null | head -n 1)
          if [ -n "$LATEST_REPORT" ]; then
            echo "Copying $LATEST_REPORT to index.html"
            cp "$LATEST_REPORT" index.html
            # Also copy to docs folder for GitHub Pages from branch
            mkdir -p ../../docs
            cp "$LATEST_REPORT" ../../docs/index.html
          else
            echo "No report files found"
            exit 1
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public/reports'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4